# Generated by Django 4.2.1 on 2023-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_name_remove_contact_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='defaultName', max_length=122),
        ),
    ]
