# Generated by Django 4.2.1 on 2023-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1234567890, max_length=12),
        ),
    ]
